In [1]:
from replay_memory import ReplayMemory
import torch
from environment import BreakoutWrapper
from dqn_model import DQN
from agent import Agent

import gymnasium as gym
from gymnasium.wrappers import RecordVideo
import ale_py
gym.register_envs(ale_py)

device = "cuda" if torch.cuda.is_available() else "mps" if torch.mps.is_available() else "cpu"

In [2]:
env = BreakoutWrapper(game="ALE/Breakout-v5", device=device)
n_actions = env.env.action_space.n

model = DQN(n_actions=n_actions, device=device)
agent = Agent(model=model, start_eps=1.0, nb_actions=n_actions, nb_warmup=10000, memory_capacity=100000, batch_size=32, device=device, learning_rate=0.00025)


A.L.E: Arcade Learning Environment (version 0.11.2+ecc1138)
[Powered by Stella]


Starting: eps = 1.0 - eps decay = -9e-05


In [3]:
state,_ = env.reset()
print(state.shape)  # Should print torch.Size([1, 4, 84, 84])

torch.Size([1, 4, 84, 84])


In [4]:
env.frame_stack

deque([tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 ...,
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.]]]], device='mps:0'),
       tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 ...,
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.]]]], device='mps:0'),
       tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 ...,
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.],
                 [0., 0., 0.,  ..., 0., 0., 0.]]]], device='m

In [11]:
import random

action = random.randint(0, n_actions - 1)
next_state, reward, done, info = env.step(action)
print(next_state.shape)  # Should print torch.Size([1, 4, 84, 84])

torch.Size([1, 4, 84, 84])


In [12]:
env.frame_stack

deque([tensor([[[[0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 [0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 [0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 ...,
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]],
              device='mps:0'),
       tensor([[[[0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 [0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 [0.5569, 0.5569, 0.5569,  ..., 0.5569, 0.5569, 0.5569],
                 ...,
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
                 [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]]],
              device='mps:0'),
       tenso